package com.lawground.global.error;

public enum ErrorCode {
    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    REQUEST_FAILED,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    DUPLICATE_QUESTION,
    PAYLOAD_TOO_LARGE,
    INTERNAL_SERVER_ERROR
}
